{{- $kubeTargetVersion := default .Capabilities.KubeVersion.GitVersion .Values.kubeTargetVersionOverride }}
{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.19-0" $kubeTargetVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $kubeTargetVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: {{ .Values.ingress.apiVersion }}
{{- end }}
kind: Ingress
metadata:
  labels:
    "app.kubernetes.io/name": '{{ template "app.name" .}}'
    {{- if .Values.renderHelmLabels }}
    "helm.sh/chart": "{{ template "app.label" .}}"
    {{- end }}
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: '{{ include "app.name" . }}-{{ include "app.env" . }}-ingress'
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
{{- end }}
  rules:
  - http:
      paths:
{{- if empty (.Values.ingress.paths) }}
      - backend:
{{- if semverCompare ">=1.19-0" $kubeTargetVersion }}
          service:
            name: '{{ include "app.name" . }}-{{ include "app.env" . }}-svc'
            port:
              number: {{ .Values.containerPort }}
        pathType: ImplementationSpecific
{{- else }}
          serviceName: '{{ include "app.name" . }}-{{ include "app.env" . }}-svc'
          servicePort: {{ .Values.containerPort }}
{{- end }}
{{- if .Values.ingress.path }}
        path: {{ .Values.ingress.path }}
{{- end -}}
{{- else }}
{{ tpl (toYaml .Values.ingress.paths | indent 6) . }}
{{- end -}}
{{- if .Values.ingress.hostName }}
    host: {{ .Values.ingress.hostName | quote }}
{{- end }}
{{- if .Values.ingress.resourceRootUrl }}
  - http:
      paths:
      - backend:
{{- if semverCompare ">=1.19-0" $kubeTargetVersion }}
          service:
            name: '{{ include "app.name" . }}-{{ include "app.env" . }}-svc'
            port:
              number: {{ .Values.containerPort }}
        pathType: ImplementationSpecific
{{- else }}
          serviceName: '{{ include "app.name" . }}-{{ include "app.env" . }}-svc'
          servicePort: {{ .Values.containerPort }}
{{- end }}
    host: {{ .Values.ingress.resourceRootUrl | quote }}
{{- end }}
{{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: '{{ include "app.name" . }}-{{ include "app.env" . }}-tls'
      hosts:
        - {{ .Values.ingress.hostName | quote }}
{{- end -}}
{{- end }}
