{{- if .Values.statefulset.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "app.name" . }}-{{ include "app.env" . }}-pvc'
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.statefulset.persistentVolumeClaim.size }}
{{- end }}


{{- if or ( .Values.deployment.enabled ) ( .Values.statefulset.enabled ) }}
{{- range $type, $attrib := .Values.volumes }}

{{- if eq $type "persistentVolumeClaim" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ include "app.name" $ }}-{{ include "app.env" $ }}-pvc'
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{- with $attrib.accessModes }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  resources:
    requests:
      storage: {{ $attrib.requests }}
    limits:
      storage: {{ $attrib.limits }}
{{- end }}

{{- end }}
{{- end }}
