version: '3.3'
services:
  nfs_server:
    image: erichough/nfs-server:2.2.1
    container_name: nfs_server
    privileged: true
    env_file:
      - .env
    ports:
      - 2049:2049 # Only this port is exposed for NFS client 4.x

      # Uncomment the following ports if using NFS client 3.x
      # - 2049:2049/udp
      # - 111:111
      # - 111:111/udp
      # - 32765:32765
      # - 32765:32765/udp
      # - 32767:32767
      # - 32767:32767/udp
    volumes:
      # To mount the volume
      - "${DATA_DIR}/data:/srv/nfs"
    restart: unless-stopped
