---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # name: <namespace>-<role_name>
  name: debug-developers-view-exec
  # namespace name where this rolebinding should apply
  namespace: debug
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # specify which role you would like to assign
  name: developers-view-exec
subjects:
  # List of users to whom we want to give access
  - kind: ServiceAccount
    namespace: kube-system
    name: firstname1.lastname1

  - kind: ServiceAccount
    namespace: kube-system
    name: firstname2.lastname2

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # name: <namespace>-<role_name>
  name: debug-developers-edit
  # namespace name where this rolebinding should apply
  namespace: debug
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # specify which role you would like to assign
  name: developers-edit
subjects:
  # List of users to whom we want to give access
  - kind: ServiceAccount
    namespace: kube-system
    name: firstname3.lastname3
