---

# - debug:
#     msg: "{{ users[user_name] }}"

- name: Ensure the given groups exist for user - '{{ user_name }}'
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ users[user_name].groups }}"


- name: Allow sudo access without password (NOPASSWD) for given groups
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ item }}'
    line: '%{{ item }} ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
  with_items: "{{ users[user_name].groups }}"

- name: Create OS user - '{{ user_name}}'
  user:
    name: "{{ user_name }}"
    state: present

- name: Add user - '{{ user_name }}' to given groups
  user:
    name: "{{ user_name }}"
    groups: "{{ users[user_name].groups }}"
    append: yes

- name: Allow SSH access to user - '{{ user_name }}'
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ users[user_name].ssh_keys }}"
