---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: besu-exec-client-ln3
  namespace: testnet
spec:
  selector:
    matchLabels:
      app: besu-exec-client-ln3
      app.kubernetes.io/name: besu-exec-client-ln3
      app.kubernetes.io/instance: besu-exec-client-ln3
  serviceName: besu-exec-client-svc-ln3
  replicas: 1
  template:
    metadata:
      labels:
        app: besu-exec-client-ln3
        app.kubernetes.io/name: besu-exec-client-ln3
        app.kubernetes.io/instance: besu-exec-client-ln3
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - sa-ln3
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 1000
      containers:
      - name: besu-exec-client-ln3
        image: hyperledger/besu:23.10.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8551    #engine
        - containerPort: 30303   #json-rpc
        - containerPort: 9545    #Metrics
        env:
          # - name: POD_IP
        command:
        - "/bin/sh"
        - "-c"
        args:
          - |
            exec /opt/besu/bin/besu \
            --config-file=/etc/besu/config.toml \
            --engine-rpc-enabled --network=goerli  --engine-host-allowlist="*" \
            --engine-jwt-secret=/jwt/jwt.hex --Xdns-enabled=true --Xdns-update-enabled=true \
            --Xnat-kube-service-name=besu-exec-client --sync-mode=X_CHECKPOINT --data-storage-format=BONSAI
        volumeMounts:
        - name: besu-config
          mountPath: /etc/besu
          readOnly: true
        - name: besu-jwt-pvc-ln3
          mountPath: /jwt
        - name: besu-pvc-ln3
          mountPath: /data/besu
      volumes:
      - name: besu-config
        configMap:
          name: besu-exec-client-cm-ln3
  volumeClaimTemplates:
    - metadata:
        name: besu-pvc-ln3
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 700Gi
        storageClassName: microk8s-hostpath
    - metadata:
        name: besu-jwt-pvc-ln3
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Mi
        storageClassName: microk8s-hostpath


---
apiVersion: v1
kind: Service
metadata:
  name: besu-exec-client-svc-ln3
  namespace: testnet
  labels:
    app: besu-exec-client-svc-ln3
    app.kubernetes.io/name: besu-exec-client-svc-ln3
    app.kubernetes.io/instance: besu-exec-client-svc-ln3
spec:
  selector:
    app: besu-exec-client-ln3
    app.kubernetes.io/name: besu-exec-client-ln3
  ports:
    - name: json-rpc
      port: 8551
      targetPort: 8551
      protocol: TCP
    - name: ws
      port: 8546
      targetPort: 8546
      protocol: TCP
    - name: metrics
      port: 9545
      targetPort: 9545
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: besu-exec-client-rpc-svc-ln3
  namespace: testnet
  labels:
    app: besu-exec-client-rpc-svc-ln3
    app.kubernetes.io/name: besu-exec-client-rpc-svc-ln3
    app.kubernetes.io/instance: besu-exec-client-rpc-svc-ln3
spec:
  type: NodePort
  selector:
    app: besu-exec-client-ln3
    app.kubernetes.io/name: besu-exec-client-ln3
    app.kubernetes.io/instance: besu-exec-client-ln3
  ports:
    - name: rlpx
      port: 30303
      targetPort: 30303
      nodePort: 30306
      protocol: TCP
    - name: discovery
      port: 30303
      targetPort: 30303
      nodePort: 30306
      protocol: UDP


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: besu-exec-client-cm-ln3
  labels:
    app: besu-exec-client-cm-ln3
    namespace: testnet
    app.kubernetes.io/name: besu-exec-client-cm-ln3
  namespace: testnet
data:
  config.toml: |-
    # Every possible CLI should be in this file.
    #
    # Please use a plausible value, besu has to at least be able to parse it.
    # If it is a multi-valued CLI make it a TOML array.
    # If it is a number or boolean make it a number or boolean
    # All other config options are strings, and must be quoted.

    # # Node Information
    data-path="/data/besu"
    # genesis-file="/etc/genesis/genesis.json"
    # logging="INFO"
    # node-private-key-file="/keys/nodekey"

    # # Transaction Pool
    # tx-pool-retention-hours=999
    # tx-pool-max-size=1024

    # # P2P network
    p2p-enabled=true
    # discovery-enabled=true
    # static-nodes-file="/config/static/static-nodes.json"
    # p2p-host="0.0.0.0"
    # p2p-port=30303
    # max-peers=50

    host-allowlist=["*"]

    # # JSON-RPC
    rpc-http-enabled=true
    rpc-http-host="0.0.0.0"
    rpc-http-cors-origins=["*"]
    # rpc-http-port=8545
    # rpc-http-api=["DEBUG","ETH", "MINER", "ADMIN", "WEB3", "IBFT", "NET", "TRACE", "EEA", "PRIV", "QBFT", "PERM", "TXPOOL"]
    # rpc-http-authentication-enabled=false
    # revert-reason-enabled=true

    # # WebSockets API
    rpc-ws-enabled=true
    rpc-ws-host="0.0.0.0"
    # rpc-ws-port=8546
    # rpc-ws-api=["DEBUG","ETH", "MINER", "ADMIN", "WEB3", "IBFT", "NET", "TRACE", "EEA", "PRIV", "QBFT", "PERM", "TXPOOL"]
    # rpc-ws-authentication-enabled=false

    # # Permissioning
    # permissions-nodes-config-file-enabled=true
    # permissions-nodes-config-file="/etc/permissions/permissions_config.toml"
    # permissions-accounts-config-file-enabled=false
    # permissions-accounts-config-file="/etc/permissions/permissions_config.toml"
    # permissions-nodes-contract-enabled=true
    # permissions-nodes-contract-address="0x0000000000000000000000000000000000009999"
    # permissions-accounts-contract-enabled=true
    # permissions-accounts-contract-address="0x0000000000000000000000000000000000008888"

    # # Metrics
    metrics-enabled=true
    metrics-host="0.0.0.0"
    metrics-port=9545

    # #Network
    # #bootnode-enabled=true
    # bootnodes=["enode://7db65cae5ed4300fd1ad40ddff269f8d39dc336f81024931ff18813cd752038d1e35be14a7a9d87ee82c6b68328c78a612fe665593d4ceac73f6b8899bca0988@besu-node-bootnode-1-0.besu-node-bootnode-1.besu.svc.cluster.local:30303", "enode://d358978a6412a9b529bdffca6dd9cfbb7e8feb8db2c9430f4cee34d0cd8d77cbdfa9bcf333a91ec456d0abca9043dc2fb5f45e28653178a19e95b4bb47e3bcbf@besu-node-bootnode-2-0.besu-node-bootnode-2.besu.svc.cluster.local:30303"]
