// The encrypt key is generated by this command:
// python3 -c 'import os;import base64;print(base64.b64encode(os.urandom(32)).decode("utf-8"))'
// is random and unique for each environment

// <project_name>-<app_name>-<env>
terraform {
  backend "remote" {
    organization = "demo-org01"

    workspaces {
      name = "demo-web-test"
    }
  }
}


data "terraform_remote_state" "core" {
  backend = "remote"

  config = {
    organization = "demo-org01"
    workspaces = {
      name = "demo-core-test"
    }
  }
}


// data "terraform_remote_state" "core-production" {
//   backend = "remote"

//   config = {
//     organization = "Create organization"
//     workspaces = {
//       name = "Update remote state here"
//     }
//   }
// }



// terraform {
//   backend "s3" {
//     bucket = "mybucket"
//     key    = "path/to/my/key"
//     region = "us-east-1"
//   }
// }
