{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ include "app.name" . }}-{{ include "app.env" . }}'
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: '{{ include "app.name" . }}-{{ include "app.env" . }}-sa'
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: '{{ include "app.name" . }}-{{ include "app.env" . }}'
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.job.command | nindent 12 }}
          args:
            {{- toYaml .Values.job.args | nindent 12 }}
          envFrom:
            - secretRef:
                name: '{{ include "app.name" . }}-{{ include "app.env" . }}-secret'
            - configMapRef:
                name: '{{ include "app.name" . }}-{{ include "app.env" . }}-configmap'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.probes }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      restartPolicy: OnFailure
  backoffLimit: {{ int .Values.job.backoffLimit }}
  completions: {{ int .Values.job.completions }}
  parallelism: {{ int .Values.job.parallelism }}
{{- end }}
