type: "hashicorp"
keyType: "BLS"
tlsEnabled: "true"
keyPath: "/v1/kv/data/kv/100_keys/1"
keyName: "value"
tlsKnownServersPath: "/web3config/knownClients.txt"
serverHost: "vault-svc"
serverPort: "8200"
timeout: "10000"
token: "hvs.DgBs2KFvUZbf1Q8lTtib4jbv"
---
type: "hashicorp"
keyType: "BLS"
tlsEnabled: "true"
keyPath: "/v1/kv/data/kv/100_keys/2"
keyName: "value"
tlsKnownServersPath: "/web3config/knownClients.txt"
serverHost: "vault-svc"
serverPort: "8200"
timeout: "10000"
token: "hvs.DgBs2KFvUZbf1Q8lTtib4jbv"
