---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developers-view
rules:
  - apiGroups:
      - "*"
    resources:
      - bindings
      - configmaps
      - controllerrevisions
      - daemonsets
      - daemonsets/status
      - deployments
      - deployments/rollback
      - deployments/scale
      - deployments/status
      - endpoints
      - events
      - horizontalpodautoscalers
      - horizontalpodautoscalers/status
      - ingresses
      - ingresses/status
      - jobs
      - jobs/status
      - limitranges
      - poddisruptionbudgets
      - poddisruptionbudgets/status
      - pods
      - pods/attach
      - pods/binding
      - pods/eviction
      - pods/log
      - pods/status
      - podtemplates
      - replicasets
      - replicasets/scale
      - replicasets/status
      - replicationcontrollers
      - replicationcontrollers/scale
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
      - rolebindings
      - roles
      - services
      - services/status
      - statefulsets
      - statefulsets/scale
      - statefulsets/status

      # Cluster scope
      - clusterroles
      - clusterrolebindings
      - namespaces
      - namespaces/finalize
      - namespaces/status
      - nodes
      - nodes/status
      - apiservices
      - apiservices/status
    verbs:
      - list
      - get
      - watch
