---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developers-view-exec
rules:
- apiGroups:
  - "*"
  resources:
  - pods/exec
  - pods/proxy
  - services/proxy
  verbs:
  - create
  - delete
  - get
  - patch
  - update

