apiVersion: v1
kind: Service
metadata:
  name: appname-web
  namespace: appname-qa
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: appname-web
