version: '2.2'
services:
  apm:
    image: docker.elastic.co/apm/apm-server:7.15.1
    container_name: apm-server
    profiles:
      - apm
      - logging
    command: --strict.perms=false -e    # -e flag to log to stderr and disable syslog/file output
    env_file:
    #  - .env
      - .env.apm
    ports:
      - 8200:8200
    volumes:
      - "./configs/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro"
    restart: unless-stopped
    networks:
      - esnet
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # Sets the maximum size of the log file
        max-file: "10"    # Sets the maximum number of log files to retain
    healthcheck:
       test: curl -s http://localhost:8200 >/dev/null || exit 1
       interval: 30s
       timeout: 10s
       retries: 50

networks:
  esnet:
