version: '2.2'
services:
  kibana:
    image: kibana:8.8.1
    #image: kibana:8.6.2
    container_name: kibana01
    profiles:
     - kibana
     - logging
    env_file:
    #  - .env
      - .env.kibana
    ports:
      - 5601:5601
        #    volumes:
        #      - ./certs/elastic-certificates.p12:/usr/share/kibana/config/certs/elastic-certificates.p12:ro
    user: "1000:1000"
    restart: unless-stopped
    networks:
      - esnet
    healthcheck:
       test: curl -s http://localhost:5601 >/dev/null || exit 1
       interval: 30s
       timeout: 10s
       retries: 50
    logging:
      driver: "json-file"
      options:
        max-size: "200k"  # Sets the maximum size of the log file
        max-file: "10"    # Sets the maximum number of log files to retain
networks:
  esnet:
