---
apiVersion: v1
kind: Secret
metadata:
  name: keys-appname-api
  namespace: appname-qa
type: Opaque
data:
  DB_HOST: cGctc2Vy=
  DB_PORT: NTQswD==
  DB_USERNAME: b21ub21u=
  DB_PASSWORD: M28yUM28yUM28yUM28yU=
  DB_NAME: b2b2b2==
  SECRET_KEY_BASE: NWFtNWFtNWFtNWFtNWFtNWFtNWFtNWFtNWFtNWFtNWFt=
  AWS_ACCESS_KEY_ID: MzRhMzRhMzRhMzRhMzRhMzRhMzRhMzRhMzRh==
  AWS_SECRET_ACCESS_KEY: VUdVUdVUdVUdVUd=
  AWS_REGION: c2Zvc2Zvc2Zvc2Zvc2Zvc2Zv
  AWS_ENDPOINT: TmVTmVTmVTmVTmVTmVTmV==

# # echo -n 'secrettext'  | base64
